# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/BR1024FIFO512/BR1024FIFO512.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BR1024FIFO512 || ORIG_REF_NAME==BR1024FIFO512} -quiet] -quiet
