# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16.xci
# IP: The module: 'BR1024FIFO16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16.xdc
# XDC: The top module name and the constraint reference have the same name: 'BR1024FIFO16'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BR1024FIFO16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16.xci
# IP: The module: 'BR1024FIFO16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16.xdc
# XDC: The top module name and the constraint reference have the same name: 'BR1024FIFO16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/BR1024FIFO16/BR1024FIFO16_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BR1024FIFO16'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
