# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/FPMul/FPMul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FPMul || ORIG_REF_NAME==FPMul} -quiet] -quiet

# IP: ip/SR32Lat15/SR32Lat15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SR32Lat15 || ORIG_REF_NAME==SR32Lat15} -quiet] -quiet
