# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/FPMul/FPMul.xci
# IP: The module: 'FPMul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/FPMul/FPMul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPMul'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/FPMul/FPMul.xci
# IP: The module: 'FPMul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Heat2D/Heat2D.srcs/sources_1/ip/FPMul/FPMul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FPMul'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
