# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pedro.rosso/stencil/stencil/Jacobi1D/Jacobi1D.srcs/sources_1/ip/SR32Lat7/SR32Lat7.xci
# IP: The module: 'SR32Lat7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Jacobi1D/Jacobi1D.srcs/sources_1/ip/SR32Lat7/SR32Lat7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SR32Lat7'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/pedro.rosso/stencil/stencil/Jacobi1D/Jacobi1D.srcs/sources_1/ip/SR32Lat7/SR32Lat7.xci
# IP: The module: 'SR32Lat7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pedro.rosso/stencil/stencil/Jacobi1D/Jacobi1D.srcs/sources_1/ip/SR32Lat7/SR32Lat7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SR32Lat7'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
