# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/FPSum/FPSum.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FPSum || ORIG_REF_NAME==FPSum} -quiet] -quiet
